                          <!--财务明细-->
                          <div class="nlistCont" style="display:none;">
                              <h3>财务明细</h3>
                              <p class="ntit" style="text-align:center;">1、应收明细表</p>
                              <p class="ntit"><span class="fl">截止日期：2016年8月12</span><span class="fr">单位：万元</span></p>
                              <div class="clear"></div>
                              <table width="100%" class="tab3 tab4">
                            	<tr>
                                	<th>序号</th>
                                    <th>单位名称</th>
                                    <th>应收款余额</th>
                                    <th>账龄(月)</th>
                                    <th>占百分比%</th>
                                </tr>
                                <tr>
                                	<td>1</td>
                                    <td>${coAll.jltfispCoFinancialList[0].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[0].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[0].zl}\</td>
                                    <td>${coAll.jltfispCoFinancialList[0].percent}</td>
                                </tr>
                                <tr>
                                	<td>2</td>
                                    <td>${coAll.jltfispCoFinancialList[1].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[1].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[1].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[1].percent}</td>
                                </tr>
                                <tr>
                                	<td>3</td>
                                    <td>${coAll.jltfispCoFinancialList[2].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[2].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[2].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[2].percent}</td>
                                </tr>
                                <tr>
                                	<td>4</td>
                                    <td>${coAll.jltfispCoFinancialList[3].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[3].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[3].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[3].percent}</td>
                                </tr>
                                <tr>
                                	<td>合计</td>
                                    <td>${coAll.jltfispCoFinancialList[4].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[4].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[4].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[4].percent}</td>
                                </tr>
                            </table>
                              <p class="ntit" style="text-align:center;">2、其他应收明细表</p>
                              <p class="ntit"><span class="fl">截止日期：2016年8月12</span><span class="fr">单位：万元</span></p>
                              <div class="clear"></div>
                              <table width="100%" class="tab3 tab4">
                            	<tr>
                                	<th>序号</th>
                                    <th>单位名称</th>
                                    <th>其他应收款余额</th>
                                    <th>账龄(月)</th>
                                    <th>占百分比%</th>
                                </tr>
                                <tr>
                                	<td>1</td>
                                    <td>${coAll.jltfispCoFinancialList[5].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[5].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[5].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[5].percent}</td>
                                </tr>
                                <tr>
                                	<td>2</td>
                                    <td>${coAll.jltfispCoFinancialList[6].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[6].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[6].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[6].percent}</td>
                                </tr>
                                <tr>
                                	<td>3</td>
                                    <td>${coAll.jltfispCoFinancialList[7].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[7].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[7].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[7].percent}</td>
                                </tr>
                                <tr>
                                	<td>4</td>
                                    <td>${coAll.jltfispCoFinancialList[8].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[8].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[8].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[8].percent}</td>
                                </tr>
                                <tr>
                                	<td>合计</td>
                                    <td>${coAll.jltfispCoFinancialList[9].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[9].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[9].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[9].percent}</td>
                                </tr>
                            </table>
                            <p class="ntit" style="text-align:center;">3、应付款明细表</p>
                            <p class="ntit"><span class="fl">截止日期：2016年8月12</span><span class="fr">单位：万元</span></p>
                            <div class="clear"></div>
                            <table width="100%" class="tab3 tab4">
                            	<tr>
                                	<th>序号</th>
                                    <th>单位名称</th>
                                    <th>应付款余额</th>
                                    <th>账龄(月)</th>
                                    <th>占百分比%</th>
                                </tr>
                                <tr>
                                	<td>1</td>
                                    <td>${coAll.jltfispCoFinancialList[10].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[10].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[10].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[10].percent}</td>
                                </tr>
                                <tr>
                                	<td>2</td>
                                    <td>${coAll.jltfispCoFinancialList[11].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[11].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[11].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[11].percent}</td>
                                </tr>
                                <tr>
                                	<td>3</td>
                                    <td>${coAll.jltfispCoFinancialList[12].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[12].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[12].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[12].percent}</td>
                                </tr>
                                <tr>
                                	<td>4</td>
                                    <td>${coAll.jltfispCoFinancialList[13].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[13].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[13].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[13].percent}</td>
                                </tr>
                                <tr>
                                	<td>合计</td>
                                    <td>${coAll.jltfispCoFinancialList[14].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[14].yszkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[14].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[14].percent}</td>
                                </tr>
                            </table>
                            <p class="ntit" style="text-align:center;">4、其他应付款明细表</p>
                            <p class="ntit"><span class="fl">截止日期：2016年8月12</span><span class="fr">单位：万元</span></p>
                            <div class="clear"></div>
                            <table width="100%" class="tab3 tab4">
                            	<tr>
                                	<th>序号</th>
                                    <th>单位名称</th>
                                    <th>其他应付款余额</th>
                                    <th>账龄(月)</th>
                                    <th>占百分比%</th>
                                </tr>
                                <tr>
                                	<td>1</td>
                                    <td>${coAll.jltfispCoFinancialList[15].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[15].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[15].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[15].percent}</td>
                                </tr>
                                <tr>
                                	<td>2</td>
                                    <td>${coAll.jltfispCoFinancialList[16].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[16].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[16].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[16].percent}</td>
                                </tr>
                                <tr>
                                	<td>3</td>
                                    <td>${coAll.jltfispCoFinancialList[17].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[17].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[17].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[17].percent}</td>
                                </tr>
                                <tr>
                                	<td>4</td>
                                    <td>${coAll.jltfispCoFinancialList[18].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[18].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[18].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[18].percent}</td>
                                </tr>
                                <tr>
                                	<td>合计</td>
                                    <td>${coAll.jltfispCoFinancialList[19].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[19].qtzkye}</td>
                                    <td>${coAll.jltfispCoFinancialList[19].zl}</td>
                                    <td>${coAll.jltfispCoFinancialList[19].percent}</td>
                                </tr>
                            </table>
                            <p class="ntit" style="text-align:center;">5、银行借款明细表</p>
                            <p class="ntit"><span class="fl">截止日期：2016年8月12</span><span class="fr">单位：万元</span></p>
                            <div class="clear"></div>
                            <table width="100%" class="tab3 tab4">
                            	<tr>
                                	<th>序号</th>
                                    <th>贷款银行</th>
                                    <th>贷款金额</th>
                                    <th>担保方式</th>
                                    <th>开始日期</th>
                                    <th>结束日期</th>
                                </tr>
                                <tr>
                                	<td>1</td>
                                    <td>${coAll.jltfispCoFinancialList[20].loanBank}</td>
                                    <td>${coAll.jltfispCoFinancialList[20].loanAccount}</td>
                                    <td>${coAll.jltfispCoFinancialList[20].sureMethod}</td>
                                    <td>${coAll.jltfispCoFinancialList[20].startTime?date}</td>
                                    <td>${coAll.jltfispCoFinancialList[20].endTime?date}</td>
                                </tr>
                                <tr>
                                	<td>2</td>
                                    <td>${coAll.jltfispCoFinancialList[21].loanBank}</td>
                                    <td>${coAll.jltfispCoFinancialList[21].loanAccount}</td>
                                    <td>${coAll.jltfispCoFinancialList[21].sureMethod}</td>
                                    <td>${coAll.jltfispCoFinancialList[21].startTime?date}</td>
                                    <td>${coAll.jltfispCoFinancialList[21].endTime?date}</td>
                                </tr>
                                <tr>
                                	<td>3</td>
                                    <td>${coAll.jltfispCoFinancialList[22].loanBank}</td>
                                    <td>${coAll.jltfispCoFinancialList[22].loanAccount}</td>
                                    <td>${coAll.jltfispCoFinancialList[22].sureMethod}</td>
                                    <td>${coAll.jltfispCoFinancialList[22].startTime?date}</td>
                                    <td>${coAll.jltfispCoFinancialList[22].endTime?date}</td>
                                </tr>
                                <tr>
                                	<td>4</td>
                                    <td>${coAll.jltfispCoFinancialList[23].loanBank}</td>
                                    <td>${coAll.jltfispCoFinancialList[23].loanAccount}</td>
                                    <td>${coAll.jltfispCoFinancialList[23].sureMethod}</td>
                                    <td>${coAll.jltfispCoFinancialList[23].startTime?date}</td>
                                    <td>${coAll.jltfispCoFinancialList[23].endTime?date}</td>
                                </tr>
                                <tr>
                                	<td><b>其他金融机构融资</b></td>
                                    <td colspan="2">${coAll.jltfispCoFinancialList[24].otherrz}</td>
                                    <td><b>民间融资</b></td>
                                    <td colspan="2">${coAll.jltfispCoFinancialList[25].mjjk}</td>
                                </tr>
                            </table>
                            <p class="ntit" style="text-align:center;">6、关联公司明细表</p>
                            <p class="ntit"><span class="fl">截止日期：2016年8月12</span><span class="fr">单位：万元</span></p>
                            <div class="clear"></div>
                            <table width="100%" class="tab3 tab4">
                            	<tr>
                                	<th>序号</th>
                                    <th>关联企业名称</th>
                                    <th>关系</th>
                                    <th>注册资本</th>
                                    <th>主营业务</th>
                                    <th>主营收入</th>
                                </tr>
                                <tr>
                                	<td>1</td>
                                    <td>${coAll.jltfispCoFinancialList[26].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[26].gx}</td>
                                    <td>${coAll.jltfispCoFinancialList[26].zczb}</td>
                                    <td>${coAll.jltfispCoFinancialList[26].zyyw}</td>
                                    <td>${coAll.jltfispCoFinancialList[26].zysr}</td>
                                </tr>
                                <tr>
                                	<td>2</td>
                                    <td>${coAll.jltfispCoFinancialList[27].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[27].gx}</td>
                                    <td>${coAll.jltfispCoFinancialList[27].zczb}</td>
                                    <td>${coAll.jltfispCoFinancialList[27].zyyw}</td>
                                    <td>${coAll.jltfispCoFinancialList[27].zysr}</td>
                                </tr>
                                <tr>
                                	<td>3</td>
                                     <td>${coAll.jltfispCoFinancialList[28].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[28].gx}</td>
                                    <td>${coAll.jltfispCoFinancialList[28].zczb}</td>
                                    <td>${coAll.jltfispCoFinancialList[28].zyyw}</td>
                                    <td>${coAll.jltfispCoFinancialList[28].zysr}</td>
                                </tr>
                                <tr>
                                	<td>4</td>
                                    <td>${coAll.jltfispCoFinancialList[29].company}</td>
                                    <td>${coAll.jltfispCoFinancialList[29].gx}</td>
                                    <td>${coAll.jltfispCoFinancialList[29].zczb}</td>
                                    <td>${coAll.jltfispCoFinancialList[29].zyyw}</td>
                                    <td>${coAll.jltfispCoFinancialList[29].zysr}</td>
                                </tr>
                            </table>
                          </div>