                        <!--利润表-->
                            <table width="100%" class="tab3 tab4">
                                <tr><th>项目</th><th>${coAll.jltfispCoDebt.year}年末</th><th>${coAll.jltfispCoDebt.year?number+1}年末</th><th>${coAll.jltfispCoDebt.year?number+2}年末</th><th>${coAll.jltfispCoDebt.year?number+3}年1~${coAll.jltfispCoProfit[0].month}月</th></tr>
                                <tr>
                                	<td><b>主营业务收入</b></td>
                                    <td>${coAll.jltfispCoProfit[0].mainincome}</td>
                                    <td>${coAll.jltfispCoProfit[1].mainincome}</td>
                                    <td>${coAll.jltfispCoProfit[2].mainincome}</td>
                                    <td>${coAll.jltfispCoProfit[3].mainincome}</td>
                                </tr>
                                <tr>
                                	<td>减：主营业务成本</td>
                                    <td>${coAll.jltfispCoProfit[0].maincost}</td>
                                    <td>${coAll.jltfispCoProfit[1].maincost}</td>
                                    <td>${coAll.jltfispCoProfit[2].maincost}</td>
                                    <td>${coAll.jltfispCoProfit[3].maincost}</td>
                                </tr>
                                <tr>
                                	<td>减：主营业务税金及附加</td>
                                    <td>${coAll.jltfispCoProfit[0].maintax}</td>
                                    <td>${coAll.jltfispCoProfit[1].maintax}</td>
                                    <td>${coAll.jltfispCoProfit[2].maintax}</td>
                                    <td>${coAll.jltfispCoProfit[3].maintax}</td>
                                </tr>
                                <tr>
                                	<td><b>主营业务利润(亏损以"-"号填列)</b></td>
                                    <td>${coAll.jltfispCoProfit[0].mainprofit}</td>
                                    <td>${coAll.jltfispCoProfit[1].mainprofit}</td>
                                    <td>${coAll.jltfispCoProfit[2].mainprofit}</td>
                                    <td>${coAll.jltfispCoProfit[3].mainprofit}</td>
                                </tr>
                                <tr>
                                	<td>加：其他业务利润(亏损以"-"号填列)</td>
                                    <td>${coAll.jltfispCoProfit[0].otherprofit}</td>
                                    <td>${coAll.jltfispCoProfit[1].otherprofit}</td>
                                    <td>${coAll.jltfispCoProfit[2].otherprofit}</td>
                                    <td>${coAll.jltfispCoProfit[3].otherprofit}</td>
                                </tr>
                                <tr>
                                	<td>减：营业费用</td>
                                    <td>${coAll.jltfispCoProfit[0].businesscost}</td>
                                    <td>${coAll.jltfispCoProfit[1].businesscost}</td>
                                    <td>${coAll.jltfispCoProfit[2].businesscost}</td>
                                    <td>${coAll.jltfispCoProfit[3].businesscost}</td>
                                </tr>
                                <tr>
                                	<td>减：管理费用</td>
                                    <td>${coAll.jltfispCoProfit[0].managecost}</td>
                                    <td>${coAll.jltfispCoProfit[1].managecost}</td>
                                    <td>${coAll.jltfispCoProfit[2].managecost}</td>
                                    <td>${coAll.jltfispCoProfit[3].managecost}</td>
                                </tr>
                                <tr>
                                	<td>减：财务费用</td>
                                    <td>${coAll.jltfispCoProfit[0].financecost}</td>
                                    <td>${coAll.jltfispCoProfit[1].financecost}</td>
                                    <td>${coAll.jltfispCoProfit[2].financecost}</td>
                                    <td>${coAll.jltfispCoProfit[3].financecost}</td>
                                </tr>
                                <tr>
                                	<td><b>营业利润(亏损以"-"号填列)</b></td>
                                    <td>${coAll.jltfispCoProfit[0].businessprofit}</td>
                                    <td>${coAll.jltfispCoProfit[1].businessprofit}</td>
                                    <td>${coAll.jltfispCoProfit[2].businessprofit}</td>
                                    <td>${coAll.jltfispCoProfit[3].businessprofit}</td>
                                </tr>
                                <tr>
                                	<td>加：投资收益(亏损以"-"号填列)</td>
                                    <td>${coAll.jltfispCoProfit[0].investmentincome}</td>
                                    <td>${coAll.jltfispCoProfit[1].investmentincome}</td>
                                    <td>${coAll.jltfispCoProfit[2].investmentincome}</td>
                                    <td>${coAll.jltfispCoProfit[3].investmentincome}</td>
                                </tr>
                                <tr>
                                	<td>加：营业外收入</td>
                                    <td>${coAll.jltfispCoProfit[0].otherincome}</td>
                                    <td>${coAll.jltfispCoProfit[1].otherincome}</td>
                                    <td>${coAll.jltfispCoProfit[2].otherincome}</td>
                                    <td>${coAll.jltfispCoProfit[3].otherincome}</td>
                                </tr>
                                <tr>
                                	<td>减：营业外支出</td>
                                    <td>${coAll.jltfispCoProfit[0].otherpay}</td>
                                    <td>${coAll.jltfispCoProfit[1].otherpay}</td>
                                    <td>${coAll.jltfispCoProfit[2].otherpay}</td>
                                    <td>${coAll.jltfispCoProfit[3].otherpay}</td>
                                </tr>
                                <tr>
                                	<td>减：资产减值损失</td>
                                    <td>${coAll.jltfispCoProfit[0].assetloss}</td>
                                    <td>${coAll.jltfispCoProfit[1].assetloss}</td>
                                    <td>${coAll.jltfispCoProfit[2].assetloss}</td>
                                    <td>${coAll.jltfispCoProfit[3].assetloss}</td>
                                </tr>
                                <tr>
                                	<td><b>利润总额(亏损以"-"号填列)</b></td>
                                    <td>${coAll.jltfispCoProfit[0].profitamount}</td>
                                    <td>${coAll.jltfispCoProfit[1].profitamount}</td>
                                    <td>${coAll.jltfispCoProfit[2].profitamount}</td>
                                    <td>${coAll.jltfispCoProfit[3].profitamount}</td>
                                </tr>
                                <tr>
                                	<td>减：所得税</td>
                                    <td>${coAll.jltfispCoProfit[0].incometax}</td>
                                    <td>${coAll.jltfispCoProfit[1].incometax}</td>
                                    <td>${coAll.jltfispCoProfit[2].incometax}</td>
                                    <td>${coAll.jltfispCoProfit[3].incometax}</td>
                                </tr>
                                <tr>
                                	<td><b>净利润(亏损以"-"号填列)</b></td>
                                    <td>${coAll.jltfispCoProfit[0].netprofit}</td>
                                    <td>${coAll.jltfispCoProfit[1].netprofit}</td>
                                    <td>${coAll.jltfispCoProfit[2].netprofit}</td>
                                    <td>${coAll.jltfispCoProfit[3].netprofit}</td>
                                </tr>
                            </table>                   